kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: buildkite-agent
spec:
  serviceName: buildkite-agent
  selector:
    matchLabels:
      app: buildkite-agent
  replicas: 10
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: buildkite-agent
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: buildkite-agent
          image: us.gcr.io/buildkite-test-project/buildkite-agent-node:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: BUILDKITE_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: buildkite-agent
                  key: token
            - name: BUILDKITE_BUILD_PATH
              value: /var/buildkite/builds
          volumeMounts:
            - name: docker-binary
              mountPath: /usr/bin/docker
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: ssh-keys
              mountPath: /root/.ssh/id_rsa
              subPath: id_rsa
            - name: ssh-keys
              mountPath: /root/.ssh/id_rsa.pub
              subPath: id_rsa.pub
            - name: buildkite-builds
              mountPath: /var/buildkite/builds
      volumes:
        - name: docker-binary
          hostPath:
            path: /usr/bin/docker
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: ssh-keys
          secret:
            secretName: buildkite-agent-ssh
            defaultMode: 0400
  volumeClaimTemplates:
    - metadata:
        name: buildkite-builds
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
